version: '3.3'

services:
  venuehub-api:
    container_name: venuehub-api
    restart: always
    image: node:20.10.0
    ports:
      - '4001:3007'
    volumes:
      - ./:/usr/src/venuehub
    working_dir: /usr/src/venuehub
    networks:
      - monorepo_network
    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

  venuehub-batch:
    container_name: venuehub-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - '4002:3008'
    volumes:
      - ./:/usr/src/venuehub
    working_dir: /usr/src/venuehub
    networks:
      - monorepo_network
    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo_network:
    driver: bridge
